# Generated by Django 4.2.6 on 2023-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeboDeDiscos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=30)),
                ('selo_fonografico', models.CharField(max_length=30)),
                ('ano', models.IntegerField(max_length=10)),
                ('pais', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
