# Generated by Django 4.2.6 on 2023-10-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='Genero'),
        ),
    ]
