# Generated by Django 4.2.6 on 2023-10-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_disc_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disc',
            new_name='Discs',
        ),
    ]
