# Generated by Django 4.2.6 on 2023-10-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_disc_discs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='discs',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.label'),
        ),
    ]
